### ISSUE TITLE
Multitouch Events?

### ISSUE THREAD

**Issue by zya** [williamngan/pt#3]
So, we can have something like:
````js
space.bindMultiTouch();
````
And a `onTouchAction` callback. But it needs to take in to consideration that there might be several touch events at any point.

**Comment by williamngan** [comment]
Definitely! We'll need to support touch events.

**Comment by williamngan** [comment]
@zya Mobile multi touch is now in master. Give it a try! :)

Demo (open in mobile device browser): http://williamngan.github.io/pt/demo/mobileapp.html
Demo code: https://github.com/williamngan/pt/blob/master/demo/circle.intersectCircle.mobile.js

Similar to `bindMouse`, you just need to do `space.bindTouch()`, and then use a callback of `onTouchAction` (instead of `onMouseAction`). See also `space.touchesToPoints(evt)` which is a convenient function to get the touch points as vectors.

Doc: http://williamngan.github.io/pt/docs/#func-Space-bindTouch

See if this works for you. Cheers.

**Comment by williamngan** [comment]
Mobile support is now in Pt 0.2. 

A guide to get started: http://williamngan.github.io/pt/docs/guide/mobile.html
Give it a try :)

**Comment by zya** [comment]
@williamngan thanks. apologies, I could not give you feedback earlier.

**Comment by williamngan** [comment]
@zya No worries. Thanks for taking the time to file this issue!
