### ISSUE TITLE
Add option to disable auto-resize (?)

### ISSUE THREAD

**Issue by tofuness** [williamngan/pt#6]
1. If you do a css `transform: rotateX(30deg)` on a canvas element, or any container containing a canvas element, the width/height values change.
2. If you then resize the browser window the canvas size is updated with the new width/height.
3. In my case, I wanted the actual canvas size to stay the same despite the rotation.

I fixed it by doing something like this:
```javascript
window.addEventListener('resize', () => {
    space.resize(someCanvasWidth, someCanvasHeight);
});
```
directly after `CanvasSpace` performs its auto-resize.

I don't think my solution is good since it request two extra renders for every resize event. Maybe `CanvasSpace` should have an option so that resize has to be called manually?

**Comment by williamngan** [comment]
Yes, an option for resize makes sense. Thanks for reporting.

**Comment by williamngan** [comment]
Hey @tofuness, the fix is now in master. Basically just a function call: `space.autoResize( true|false )`. For instance you can do `new CanvasSpace(...).display().autoResize(false)`, and the <canvas> element won't resize then.

http://williamngan.github.io/pt/docs/#func-CanvasSpace-autoResize

See if it works. Thanks!

**Comment by tofuness** [comment]
Works great! :smile:
